#version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3356:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ckt_network  # 네트워크 이름 변경

  admin:
    build:
      context: ./admin
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_URL}:3306/${DB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - ckt_network  # 네트워크 이름 변경

  gateway:
    build:
      context: ./gateway
    ports:
      - "8081:8081"
    depends_on:
      - admin
    networks:
      - ckt_network

volumes:
  db_data:

networks:
  ckt_network:   # 네트워크 이름 변경
    driver: bridge
