spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://172.31.32.243:8082
          predicates:
            - Path=/api/v1/auth/**

        - id: collector
          uri: http://172.31.32.243:8090
          predicates:
            - Path=/api/v1/vehicles/collector/**

        - id: admin
          uri: http://172.31.35.211:8081
          predicates:
            - Path=/api/v1/companies/**

        - id: customer
          uri: http://172.31.35.211:8081
          predicates:
            - Path=/api/v1/customers/**

        - id: vehicle
          uri: http://172.31.35.211:8081
          predicates:
            - Path=/api/v1/vehicles/**

        - id: logs
          uri: http://172.31.35.211:8081
          predicates:
            - Path=/api/v1/logs/**

cors:
  allowed-origins: http://localhost:5173
