server:
  port: 8081  # 게이트웨이 포트

spring:
  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: http://localhost:8080  # admin 
          predicates:
            - Path=/api/v1/admin/**
