server:
  port: 8081  # 게이트웨이 포트

spring:
  profiles:
    active: local

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

jwt:
  secret: ${JWT_SECRET}
  whitelist: "/api/v1/auth/login,/api/v1/auth/join,/api/v1/auth/password-reset"
