spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/**

        - id: collector
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/vehicles/collector/**

        - id: admin
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/companies/**

        - id: customer
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/customers/**

        - id: vehicle
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/vehicles/**

        - id: rentals
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/rentals/**

        - id: logs
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/logs/**

        - id: tracking
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/tracking/**

cors:
  allowed-origins: http://localhost:5173
