spring:
  application:
    name: admin

  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties.hibernate:
      default_batch_fetch_size: 1000
      globally_quoted_identifiers: true
